version: "2" # required to adjust maintainability checks
exclude_patterns:
    - "integrationTests/"
    - "**/*unit.test.js"

checks:
    argument-count:
        config:
            threshold: 6
    complex-logic:
        config:
            threshold: 5
    file-lines:
        config:
            threshold: 180
    method-complexity:
        config:
            threshold: 6
    method-count:
        config:
            threshold: 18
    method-lines:
        config:
            threshold: 40
    nested-control-flow:
        config:
            threshold: 4
    return-statements:
        config:
            threshold: 6
    similar-code:
        config:
            threshold: # language-specific defaults. an override will affect all languages.
    identical-code:
        config:
            threshold: # language-specific defaults. an override will affect all languages
